name: speech_recognizer
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  speech_to_text: ^3.1.0
  avatar_glow: ^1.2.0
  clipboard: ^0.1.2+8
  http: ^0.13.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
